name: CICD pipeline for banking application

on:
  push:
    branches: ["main"]

jobs:

  build: # 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn compile

  security-check: # 2
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v5
      - name: Security Check
        run: echo "Running security checks..."
      - name: Trivy Installation # it is security scanner to find vulnerabilities and securty issues before deploying 
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy
          
      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .

      - name: Gitleaks Installation # Gitleaks is a security tool used to detect secrets accidentally committed to
        run: sudo apt install gitleaks -y
      - name: Gitleaks code scan 
        run: gitleaks detect source . -r gitleaks-report.json -f json






        
          
  
